name: CI/CD - Chrona Backend

on:
  push:
    branches:
      - main  # triggers only on main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3️⃣ Build and push Docker image
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/chrona-backend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/chrona-backend:latest

      # 4️⃣ Deploy to EC2 via SSH
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Pulling latest Docker image..."
            docker pull ${{ secrets.DOCKER_USERNAME }}/chrona-backend:latest

            echo "Stopping old container (if exists)..."
            docker stop chrona-backend || true
            docker rm chrona-backend || true

            echo "Running new container..."
            docker run -d -p 5000:5000 --name chrona-backend ${{ secrets.DOCKER_USERNAME }}/chrona-backend:latest

            echo "Deployment completed successfully!"
